// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251028060552_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Decaf")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElevationMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElevationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Farm")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorProfile")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Importer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Process")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roast")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Varietal")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WetMill")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId", "Name")
                        .IsUnique();

                    b.ToTable("Beans", t =>
                        {
                            t.HasCheckConstraint("CK_Bean_ReleaseDate_8Digits", "(ReleaseDate IS NULL) OR (ReleaseDate >= 10000000 AND ReleaseDate <= 99999999)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RoastDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("BeanBatches");
                });

            modelBuilder.Entity("Backend.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Backend.Entities.BrewGrinderDialSetting", b =>
                {
                    b.Property<int>("BrewSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrinderDialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DialValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("BrewSettingId", "GrinderDialId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GrinderDialId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("BrewGrinderDialSettings");
                });

            modelBuilder.Entity("Backend.Entities.BrewMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BrewMethods");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeanBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bitter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrewSetupId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BrewTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrindTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WaterTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WaterVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeanBatchId");

                    b.HasIndex("BrewSetupId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId", "BrewSetupId")
                        .IsUnique()
                        .HasFilter("Recommended = 1");

                    b.ToTable("BrewSettings", t =>
                        {
                            t.HasCheckConstraint("CHK_BrewSetting_DoseOrGrindTime", "(Dose IS NOT NULL OR GrindTime IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrewerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrinderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.HasIndex("BrewerId");

                    b.HasIndex("GrinderId", "BrewerId", "BeanId")
                        .IsUnique();

                    b.ToTable("BrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrewMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelAlias")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WaterCapacity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrewMethodId");

                    b.ToTable("Brewers", t =>
                        {
                            t.HasCheckConstraint("CK_Brewer_ReleaseDate_8Digits", "(ReleaseDate IS NULL) OR (ReleaseDate >= 10000000 AND ReleaseDate <= 99999999)");

                            t.HasCheckConstraint("CK_Brewer_WaterCapacity_Positive", "(WaterCapacity IS NULL) OR (WaterCapacity > 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewerStockSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BrewTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrewerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WaterVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewerId");

                    b.ToTable("BrewerStockSettings", t =>
                        {
                            t.HasCheckConstraint("CK_BrewerStockSetting_BrewTime_Positive", "(BrewTime IS NULL) OR (BrewTime >= 0)");

                            t.HasCheckConstraint("CK_BrewerStockSetting_WaterTemperature_Positive", "(WaterTemperature IS NULL) OR (WaterTemperature >= 0)");

                            t.HasCheckConstraint("CK_BrewerStockSetting_WaterVolume_Positive", "(WaterVolume IS NULL) OR (WaterVolume >= 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewerUserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BrewTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrewerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WaterVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewerId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("BrewerUserSettings", t =>
                        {
                            t.HasCheckConstraint("CK_BrewerUserSetting_BrewTime_Positive", "(BrewTime IS NULL) OR (BrewTime >= 0)");

                            t.HasCheckConstraint("CK_BrewerUserSetting_WaterTemperature_Positive", "(WaterTemperature IS NULL) OR (WaterTemperature >= 0)");

                            t.HasCheckConstraint("CK_BrewerUserSetting_WaterVolume_Positive", "(WaterVolume IS NULL) OR (WaterVolume >= 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelAlias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Grinders", t =>
                        {
                            t.HasCheckConstraint("CK_Grinder_ReleaseDate_8Digits", "(ReleaseDate IS NULL) OR (ReleaseDate >= 10000000 AND ReleaseDate <= 99999999)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrinderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Min")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Step")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrinderId");

                    b.ToTable("GrinderDials");
                });

            modelBuilder.Entity("Backend.Entities.GrinderElementCompatibility", b =>
                {
                    b.Property<int>("GrinderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrindingElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrinderId", "GrindingElementId");

                    b.HasIndex("GrindingElementId");

                    b.ToTable("GrinderElementCompatibilities");
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrindingMechanismId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrindingMechanismId");

                    b.ToTable("GrindingElements", t =>
                        {
                            t.HasCheckConstraint("CK_GrindingElement_Diameter_Positive", "Diameter >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Entities.GrindingMechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GrindingMechanisms");
                });

            modelBuilder.Entity("Backend.Entities.Roaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Location")
                        .IsUnique();

                    b.ToTable("Roasters");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsernameUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UpdatedById");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.UserBrewSetup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrewSetupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "BrewSetupId");

                    b.HasIndex("BrewSetupId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("UserBrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.HasOne("Backend.Entities.Roaster", "Roaster")
                        .WithMany("Beans")
                        .HasForeignKey("RoasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Roaster");
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.HasOne("Backend.Entities.Bean", "Bean")
                        .WithMany("BeanBatches")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BeanBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bean");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.BrewGrinderDialSetting", b =>
                {
                    b.HasOne("Backend.Entities.BrewSetting", "BrewSetting")
                        .WithMany("BrewGrinderDialSettings")
                        .HasForeignKey("BrewSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.GrinderDial", "GrinderDial")
                        .WithMany("BrewGrinderDialSettings")
                        .HasForeignKey("GrinderDialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BrewSetting");

                    b.Navigation("CreatedBy");

                    b.Navigation("GrinderDial");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.HasOne("Backend.Entities.BeanBatch", "BeanBatch")
                        .WithMany("BrewSettings")
                        .HasForeignKey("BeanBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.BrewSetup", "BrewSetup")
                        .WithMany("BrewSettings")
                        .HasForeignKey("BrewSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BrewSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeanBatch");

                    b.Navigation("BrewSetup");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.HasOne("Backend.Entities.Bean", "Bean")
                        .WithMany("BrewSetups")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewSetups")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("BrewSetups")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bean");

                    b.Navigation("Brewer");

                    b.Navigation("Grinder");
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.HasOne("Backend.Entities.Brand", "Brand")
                        .WithMany("Brewers")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.BrewMethod", "BrewMethod")
                        .WithMany("Brewers")
                        .HasForeignKey("BrewMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("BrewMethod");
                });

            modelBuilder.Entity("Backend.Entities.BrewerStockSetting", b =>
                {
                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewerStockSettings")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("Backend.Entities.BrewerUserSetting", b =>
                {
                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewerUserSettings")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BrewerUserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brewer");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.HasOne("Backend.Entities.Brand", "Brand")
                        .WithMany("Grinders")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("GrinderDials")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grinder");
                });

            modelBuilder.Entity("Backend.Entities.GrinderElementCompatibility", b =>
                {
                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("CompatibleParts")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.GrindingElement", "GrindingElement")
                        .WithMany("CompatibleGrinders")
                        .HasForeignKey("GrindingElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grinder");

                    b.Navigation("GrindingElement");
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.HasOne("Backend.Entities.GrindingMechanism", "GrindingMechanism")
                        .WithMany("GrinderParts")
                        .HasForeignKey("GrindingMechanismId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrindingMechanism");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Backend.Entities.UserBrewSetup", b =>
                {
                    b.HasOne("Backend.Entities.BrewSetup", "BrewSetup")
                        .WithMany("UserBrewSetups")
                        .HasForeignKey("BrewSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("UserBrewSetups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrewSetup");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.HasOne("Backend.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Backend.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.Navigation("BeanBatches");

                    b.Navigation("BrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.Navigation("BrewSettings");
                });

            modelBuilder.Entity("Backend.Entities.Brand", b =>
                {
                    b.Navigation("Brewers");

                    b.Navigation("Grinders");
                });

            modelBuilder.Entity("Backend.Entities.BrewMethod", b =>
                {
                    b.Navigation("Brewers");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.Navigation("BrewGrinderDialSettings");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.Navigation("BrewSettings");

                    b.Navigation("UserBrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.Navigation("BrewSetups");

                    b.Navigation("BrewerStockSettings");

                    b.Navigation("BrewerUserSettings");
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.Navigation("BrewSetups");

                    b.Navigation("CompatibleParts");

                    b.Navigation("GrinderDials");
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.Navigation("BrewGrinderDialSettings");
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.Navigation("CompatibleGrinders");
                });

            modelBuilder.Entity("Backend.Entities.GrindingMechanism", b =>
                {
                    b.Navigation("GrinderParts");
                });

            modelBuilder.Entity("Backend.Entities.Roaster", b =>
                {
                    b.Navigation("Beans");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Navigation("BeanBatches");

                    b.Navigation("BrewSettings");

                    b.Navigation("BrewerUserSettings");

                    b.Navigation("UserBrewSetups");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
