// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<bool>("Decaf")
                        .HasColumnType("boolean")
                        .HasColumnName("decaf");

                    b.Property<int?>("ElevationMax")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_max");

                    b.Property<int?>("ElevationMin")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_min");

                    b.Property<string>("Farm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("farm");

                    b.Property<string>("FlavorProfile")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("flavor_profile");

                    b.Property<string>("Importer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("importer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Process")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("process");

                    b.Property<string>("Producer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("producer");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<string>("Roast")
                        .HasColumnType("text")
                        .HasColumnName("roast");

                    b.Property<int?>("RoasterId")
                        .HasColumnType("integer")
                        .HasColumnName("roaster_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Varietal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("varietal");

                    b.Property<string>("WetMill")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wet_mill");

                    b.HasKey("Id")
                        .HasName("pk_beans");

                    b.HasIndex("RoasterId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_beans_roaster_id_name");

                    b.ToTable("beans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bean_ReleaseDate_8Digits", "(\"release_date\" IS NULL) OR (\"release_date\" >= 10000000 AND \"release_date\" <= 99999999)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeanId")
                        .HasColumnType("integer")
                        .HasColumnName("bean_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateOnly>("RoastDate")
                        .HasColumnType("date")
                        .HasColumnName("roast_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bean_batches");

                    b.HasIndex("BeanId")
                        .HasDatabaseName("ix_bean_batches_bean_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_bean_batches_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_bean_batches_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bean_batches_user_id");

                    b.ToTable("bean_batches", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.BrewGrinderDialSetting", b =>
                {
                    b.Property<int>("BrewSettingId")
                        .HasColumnType("integer")
                        .HasColumnName("brew_setting_id");

                    b.Property<int>("GrinderDialId")
                        .HasColumnType("integer")
                        .HasColumnName("grinder_dial_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<decimal>("DialValue")
                        .HasColumnType("numeric")
                        .HasColumnName("dial_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("BrewSettingId", "GrinderDialId")
                        .HasName("pk_brew_grinder_dial_settings");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_brew_grinder_dial_settings_created_by_id");

                    b.HasIndex("GrinderDialId")
                        .HasDatabaseName("ix_brew_grinder_dial_settings_grinder_dial_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_brew_grinder_dial_settings_updated_by_id");

                    b.ToTable("brew_grinder_dial_settings", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.BrewMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brew_methods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_brew_methods_name");

                    b.ToTable("brew_methods", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeanBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("bean_batch_id");

                    b.Property<int>("Bitter")
                        .HasColumnType("integer")
                        .HasColumnName("bitter");

                    b.Property<int>("BrewSetupId")
                        .HasColumnType("integer")
                        .HasColumnName("brew_setup_id");

                    b.Property<decimal?>("BrewTime")
                        .HasColumnType("numeric")
                        .HasColumnName("brew_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("numeric")
                        .HasColumnName("dose");

                    b.Property<decimal?>("GrindTime")
                        .HasColumnType("numeric")
                        .HasColumnName("grind_time");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("Recommended")
                        .HasColumnType("boolean")
                        .HasColumnName("recommended");

                    b.Property<int>("Sour")
                        .HasColumnType("integer")
                        .HasColumnName("sour");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("water_temperature");

                    b.Property<decimal?>("WaterVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("water_volume");

                    b.HasKey("Id")
                        .HasName("pk_brew_settings");

                    b.HasIndex("BeanBatchId")
                        .HasDatabaseName("ix_brew_settings_bean_batch_id");

                    b.HasIndex("BrewSetupId")
                        .HasDatabaseName("ix_brew_settings_brew_setup_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_brew_settings_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_brew_settings_updated_by_id");

                    b.HasIndex("UserId", "BrewSetupId")
                        .IsUnique()
                        .HasDatabaseName("ix_brew_settings_user_id_brew_setup_id")
                        .HasFilter("\"recommended\" = TRUE");

                    b.ToTable("brew_settings", null, t =>
                        {
                            t.HasCheckConstraint("CHK_BrewSetting_DoseOrGrindTime", "(\"dose\" IS NOT NULL) OR (\"grind_time\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeanId")
                        .HasColumnType("integer")
                        .HasColumnName("bean_id");

                    b.Property<int>("BrewerId")
                        .HasColumnType("integer")
                        .HasColumnName("brewer_id");

                    b.Property<int>("GrinderId")
                        .HasColumnType("integer")
                        .HasColumnName("grinder_id");

                    b.HasKey("Id")
                        .HasName("pk_brew_setups");

                    b.HasIndex("BeanId")
                        .HasDatabaseName("ix_brew_setups_bean_id");

                    b.HasIndex("BrewerId")
                        .HasDatabaseName("ix_brew_setups_brewer_id");

                    b.HasIndex("GrinderId", "BrewerId", "BeanId")
                        .IsUnique()
                        .HasDatabaseName("ix_brew_setups_grinder_id_brewer_id_bean_id");

                    b.ToTable("brew_setups", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("BrewMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("brew_method_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("ModelAlias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_alias");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.Property<decimal?>("WaterCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("water_capacity");

                    b.HasKey("Id")
                        .HasName("pk_brewers");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_brewers_brand_id");

                    b.HasIndex("BrewMethodId")
                        .HasDatabaseName("ix_brewers_brew_method_id");

                    b.ToTable("brewers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Brewer_ReleaseDate_8Digits", "(\"release_date\" IS NULL) OR (\"release_date\" >= 10000000 AND \"release_date\" <= 99999999)");

                            t.HasCheckConstraint("CK_Brewer_WaterCapacity_Positive", "(\"water_capacity\" IS NULL) OR (\"water_capacity\" > 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewerStockSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BrewTime")
                        .HasColumnType("numeric")
                        .HasColumnName("brew_time");

                    b.Property<int>("BrewerId")
                        .HasColumnType("integer")
                        .HasColumnName("brewer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("water_temperature");

                    b.Property<decimal?>("WaterVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("water_volume");

                    b.HasKey("Id")
                        .HasName("pk_brewer_stock_settings");

                    b.HasIndex("BrewerId")
                        .HasDatabaseName("ix_brewer_stock_settings_brewer_id");

                    b.ToTable("brewer_stock_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BrewerStockSetting_BrewTime_Positive", "(\"brew_time\" IS NULL) OR (\"brew_time\" >= 0)");

                            t.HasCheckConstraint("CK_BrewerStockSetting_WaterTemperature_Positive", "(\"water_temperature\" IS NULL) OR (\"water_temperature\" >= 0)");

                            t.HasCheckConstraint("CK_BrewerStockSetting_WaterVolume_Positive", "(\"water_volume\" IS NULL) OR (\"water_volume\" >= 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.BrewerUserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BrewTime")
                        .HasColumnType("numeric")
                        .HasColumnName("brew_time");

                    b.Property<int>("BrewerId")
                        .HasColumnType("integer")
                        .HasColumnName("brewer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("water_temperature");

                    b.Property<decimal?>("WaterVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("water_volume");

                    b.HasKey("Id")
                        .HasName("pk_brewer_user_settings");

                    b.HasIndex("BrewerId")
                        .HasDatabaseName("ix_brewer_user_settings_brewer_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_brewer_user_settings_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_brewer_user_settings_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_brewer_user_settings_user_id");

                    b.ToTable("brewer_user_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BrewerUserSetting_BrewTime_Positive", "(\"brew_time\" IS NULL) OR (\"brew_time\" >= 0)");

                            t.HasCheckConstraint("CK_BrewerUserSetting_WaterTemperature_Positive", "(\"water_temperature\" IS NULL) OR (\"water_temperature\" >= 0)");

                            t.HasCheckConstraint("CK_BrewerUserSetting_WaterVolume_Positive", "(\"water_volume\" IS NULL) OR (\"water_volume\" >= 0)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("ModelAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_alias");

                    b.Property<int?>("ReleaseDate")
                        .HasColumnType("integer")
                        .HasColumnName("release_date");

                    b.HasKey("Id")
                        .HasName("pk_grinders");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_grinders_brand_id");

                    b.ToTable("grinders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Grinder_ReleaseDate_8Digits", "(\"release_date\" IS NULL) OR (\"release_date\" >= 10000000 AND \"release_date\" <= 99999999)");
                        });
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrinderId")
                        .HasColumnType("integer")
                        .HasColumnName("grinder_id");

                    b.Property<decimal?>("Max")
                        .HasColumnType("numeric")
                        .HasColumnName("max");

                    b.Property<decimal?>("Min")
                        .HasColumnType("numeric")
                        .HasColumnName("min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Step")
                        .HasColumnType("numeric")
                        .HasColumnName("step");

                    b.HasKey("Id")
                        .HasName("pk_grinder_dials");

                    b.HasIndex("GrinderId")
                        .HasDatabaseName("ix_grinder_dials_grinder_id");

                    b.ToTable("grinder_dials", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.GrinderElementCompatibility", b =>
                {
                    b.Property<int>("GrinderId")
                        .HasColumnType("integer")
                        .HasColumnName("grinder_id");

                    b.Property<int>("GrindingElementId")
                        .HasColumnType("integer")
                        .HasColumnName("grinding_element_id");

                    b.HasKey("GrinderId", "GrindingElementId")
                        .HasName("pk_grinder_element_compatibilities");

                    b.HasIndex("GrindingElementId")
                        .HasDatabaseName("ix_grinder_element_compatibilities_grinding_element_id");

                    b.ToTable("grinder_element_compatibilities", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Diameter")
                        .HasColumnType("numeric")
                        .HasColumnName("diameter");

                    b.Property<int>("GrindingMechanismId")
                        .HasColumnType("integer")
                        .HasColumnName("grinding_mechanism_id");

                    b.HasKey("Id")
                        .HasName("pk_grinding_elements");

                    b.HasIndex("GrindingMechanismId")
                        .HasDatabaseName("ix_grinding_elements_grinding_mechanism_id");

                    b.ToTable("grinding_elements", null, t =>
                        {
                            t.HasCheckConstraint("CK_GrindingElement_Diameter_Positive", "\"diameter\" >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Entities.GrindingMechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_grinding_mechanisms");

                    b.ToTable("grinding_mechanisms", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Roaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_address");

                    b.Property<Point>("LocationCoordinates")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location_coordinates");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_roasters");

                    b.HasIndex("Name", "LocationAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_roasters_name_location_address");

                    b.ToTable("roasters", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<DateTime?>("UsernameUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_updated_at");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_asp_net_users_updated_by_id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.UserBrewSetup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BrewSetupId")
                        .HasColumnType("integer")
                        .HasColumnName("brew_setup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("UserId", "BrewSetupId")
                        .HasName("pk_user_brew_setups");

                    b.HasIndex("BrewSetupId")
                        .HasDatabaseName("ix_user_brew_setups_brew_setup_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_brew_setups_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_brew_setups_updated_by_id");

                    b.ToTable("user_brew_setups", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.HasOne("Backend.Entities.Roaster", "Roaster")
                        .WithMany("Beans")
                        .HasForeignKey("RoasterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_beans_roasters_roaster_id");

                    b.Navigation("Roaster");
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.HasOne("Backend.Entities.Bean", "Bean")
                        .WithMany("BeanBatches")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bean_batches_beans_bean_id");

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bean_batches_asp_net_users_created_by_id");

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bean_batches_asp_net_users_updated_by_id");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BeanBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bean_batches_asp_net_users_user_id");

                    b.Navigation("Bean");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.BrewGrinderDialSetting", b =>
                {
                    b.HasOne("Backend.Entities.BrewSetting", "BrewSetting")
                        .WithMany("BrewGrinderDialSettings")
                        .HasForeignKey("BrewSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brew_grinder_dial_settings_brew_settings_brew_setting_id");

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brew_grinder_dial_settings_users_created_by_id");

                    b.HasOne("Backend.Entities.GrinderDial", "GrinderDial")
                        .WithMany("BrewGrinderDialSettings")
                        .HasForeignKey("GrinderDialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_grinder_dial_settings_grinder_dials_grinder_dial_id");

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brew_grinder_dial_settings_users_updated_by_id");

                    b.Navigation("BrewSetting");

                    b.Navigation("CreatedBy");

                    b.Navigation("GrinderDial");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.HasOne("Backend.Entities.BeanBatch", "BeanBatch")
                        .WithMany("BrewSettings")
                        .HasForeignKey("BeanBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_settings_bean_batches_bean_batch_id");

                    b.HasOne("Backend.Entities.BrewSetup", "BrewSetup")
                        .WithMany("BrewSettings")
                        .HasForeignKey("BrewSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_settings_brew_setups_brew_setup_id");

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brew_settings_asp_net_users_created_by_id");

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brew_settings_asp_net_users_updated_by_id");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BrewSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_settings_asp_net_users_user_id");

                    b.Navigation("BeanBatch");

                    b.Navigation("BrewSetup");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.HasOne("Backend.Entities.Bean", "Bean")
                        .WithMany("BrewSetups")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_setups_beans_bean_id");

                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewSetups")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_setups_brewers_brewer_id");

                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("BrewSetups")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brew_setups_grinders_grinder_id");

                    b.Navigation("Bean");

                    b.Navigation("Brewer");

                    b.Navigation("Grinder");
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.HasOne("Backend.Entities.Brand", "Brand")
                        .WithMany("Brewers")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brewers_brands_brand_id");

                    b.HasOne("Backend.Entities.BrewMethod", "BrewMethod")
                        .WithMany("Brewers")
                        .HasForeignKey("BrewMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_brewers_brew_methods_brew_method_id");

                    b.Navigation("Brand");

                    b.Navigation("BrewMethod");
                });

            modelBuilder.Entity("Backend.Entities.BrewerStockSetting", b =>
                {
                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewerStockSettings")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brewer_stock_settings_brewers_brewer_id");

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("Backend.Entities.BrewerUserSetting", b =>
                {
                    b.HasOne("Backend.Entities.Brewer", "Brewer")
                        .WithMany("BrewerUserSettings")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brewer_user_settings_brewers_brewer_id");

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brewer_user_settings_asp_net_users_created_by_id");

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_brewer_user_settings_asp_net_users_updated_by_id");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("BrewerUserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brewer_user_settings_asp_net_users_user_id");

                    b.Navigation("Brewer");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.HasOne("Backend.Entities.Brand", "Brand")
                        .WithMany("Grinders")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_grinders_brands_brand_id");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("GrinderDials")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grinder_dials_grinders_grinder_id");

                    b.Navigation("Grinder");
                });

            modelBuilder.Entity("Backend.Entities.GrinderElementCompatibility", b =>
                {
                    b.HasOne("Backend.Entities.Grinder", "Grinder")
                        .WithMany("CompatibleParts")
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grinder_element_compatibilities_grinders_grinder_id");

                    b.HasOne("Backend.Entities.GrindingElement", "GrindingElement")
                        .WithMany("CompatibleGrinders")
                        .HasForeignKey("GrindingElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grinder_element_compatibilities_grinding_elements_grinding_");

                    b.Navigation("Grinder");

                    b.Navigation("GrindingElement");
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.HasOne("Backend.Entities.GrindingMechanism", "GrindingMechanism")
                        .WithMany("GrinderParts")
                        .HasForeignKey("GrindingMechanismId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grinding_elements_grinding_mechanisms_grinding_mechanism_id");

                    b.Navigation("GrindingMechanism");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asp_net_users_asp_net_users_updated_by_id");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Backend.Entities.UserBrewSetup", b =>
                {
                    b.HasOne("Backend.Entities.BrewSetup", "BrewSetup")
                        .WithMany("UserBrewSetups")
                        .HasForeignKey("BrewSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_brew_setups_brew_setups_brew_setup_id");

                    b.HasOne("Backend.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_brew_setups_asp_net_users_created_by_id");

                    b.HasOne("Backend.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_brew_setups_asp_net_users_updated_by_id");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("UserBrewSetups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_brew_setups_asp_net_users_user_id");

                    b.Navigation("BrewSetup");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.HasOne("Backend.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Backend.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Backend.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Backend.Entities.Bean", b =>
                {
                    b.Navigation("BeanBatches");

                    b.Navigation("BrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.BeanBatch", b =>
                {
                    b.Navigation("BrewSettings");
                });

            modelBuilder.Entity("Backend.Entities.Brand", b =>
                {
                    b.Navigation("Brewers");

                    b.Navigation("Grinders");
                });

            modelBuilder.Entity("Backend.Entities.BrewMethod", b =>
                {
                    b.Navigation("Brewers");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetting", b =>
                {
                    b.Navigation("BrewGrinderDialSettings");
                });

            modelBuilder.Entity("Backend.Entities.BrewSetup", b =>
                {
                    b.Navigation("BrewSettings");

                    b.Navigation("UserBrewSetups");
                });

            modelBuilder.Entity("Backend.Entities.Brewer", b =>
                {
                    b.Navigation("BrewSetups");

                    b.Navigation("BrewerStockSettings");

                    b.Navigation("BrewerUserSettings");
                });

            modelBuilder.Entity("Backend.Entities.Grinder", b =>
                {
                    b.Navigation("BrewSetups");

                    b.Navigation("CompatibleParts");

                    b.Navigation("GrinderDials");
                });

            modelBuilder.Entity("Backend.Entities.GrinderDial", b =>
                {
                    b.Navigation("BrewGrinderDialSettings");
                });

            modelBuilder.Entity("Backend.Entities.GrindingElement", b =>
                {
                    b.Navigation("CompatibleGrinders");
                });

            modelBuilder.Entity("Backend.Entities.GrindingMechanism", b =>
                {
                    b.Navigation("GrinderParts");
                });

            modelBuilder.Entity("Backend.Entities.Roaster", b =>
                {
                    b.Navigation("Beans");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Navigation("BeanBatches");

                    b.Navigation("BrewSettings");

                    b.Navigation("BrewerUserSettings");

                    b.Navigation("UserBrewSetups");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
